# Generated by Django 4.0.4 on 2022-04-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=70)),
                ('Lastname', models.CharField(max_length=70)),
                ('Email', models.CharField(max_length=70)),
                ('Contact', models.BigIntegerField()),
                ('Username', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=70)),
                ('Lastname', models.CharField(max_length=70)),
                ('Email', models.CharField(max_length=70)),
                ('Contact', models.BigIntegerField()),
                ('Username', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
