# Generated by Django 4.0.4 on 2022-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorId', models.CharField(max_length=50)),
                ('PatientId', models.CharField(max_length=500)),
                ('Dates', models.CharField(max_length=500)),
                ('Slots', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='C_fees',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Experience',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Slots',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Speciality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='Date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='Link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='Time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
