# Generated by Django 4.0.4 on 2022-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_doctor_c_fees_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Wallet',
            field=models.BigIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='Wallet',
            field=models.BigIntegerField(default=''),
        ),
    ]
